kind: Namespace
apiVersion: v1
metadata:
    name: nav-bff-v2
    labels:
        app: nav-bff-scheduling-services
        cloud: azure
        environment: dev
        cc: 'A04087D476'
        journey: NAV
        oi: '600001290'
        product: NavPacientes
        tier: t0

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nav-bff-scheduling-services-dev
    namespace: nav-bff-v2
data:
    env: 'dev'
    userName: 'admin'
    apm.server_urls: 'https://apm-hydrav2.dasaexp.io:443'

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nav-bff-scheduling-services
    namespace: nav-bff-v2
    labels:
        app: nav-bff-scheduling-services
        cloud: azure
        environment: dev
        cc: 'A04087D476'
        journey: NAV
        oi: '600001290'
        product: NavPacientes
        tier: t0
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    replicas: 5
    selector:
        matchLabels:
            app: nav-bff-scheduling-services
    template:
        metadata:
            namespace: nav-bff-v2
            labels:
                app: nav-bff-scheduling-services
                cloud: azure
                environment: dev
                cc: 'A04087D476'
                journey: NAV
                oi: '600001290'
                product: NavPacientes
                tier: t0
        spec:
            imagePullSecrets:
                - name: imagesdasa
            containers:
                - name: nav-bff-scheduling-services
                  image: ${IMAGE_VERSION}
                  envFrom:
                      - configMapRef:
                            name: nav-bff-envs
                      - configMapRef:
                            name: nav-bff-scheduling-services-dev
                    #   - secretRef:
                    #         name: bff-key
                  ports:
                      - containerPort: 3335
                  livenessProbe:
                      httpGet:
                          path: /.well-known/apollo/server-health
                          port: 3335
                          httpHeaders:
                              - name: Host #isDefined(localhost)
                                value: localhost #isDefined(localhost)
                      initialDelaySeconds: 120
                      periodSeconds: 240
                      timeoutSeconds: 240
                      successThreshold: 1
                      failureThreshold: 3
                  readinessProbe:
                      httpGet:
                          path: /.well-known/apollo/server-health
                          port: 3335
                          httpHeaders:
                              - name: Host #isDefined(localhost)
                                value: localhost #isDefined(localhost)
                      initialDelaySeconds: 30
                      periodSeconds: 30
                      timeoutSeconds: 120
                      successThreshold: 1
                      failureThreshold: 6
                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '150m'
                      limits:
                          memory: '512Mi'
                          cpu: '600m'
            tolerations:
                - key: "kubernetes.azure.com/scalesetpriority"
                  operator: "Equal"
                  value: "spot"
                  effect: "NoSchedule"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    namespace: nav-bff-v2
    name: nav-bff-scheduling-services-dev-hpa
    labels:
        app: nav-bff-scheduling-services
        cloud: azure
        environment: dev
        cc: 'A04087D476'
        journey: NAV
        oi: '600001290'
        product: NavPacientes
        tier: t0
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nav-bff-scheduling-services
    minReplicas: 2
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 90
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 70

---
kind: Service
apiVersion: v1
metadata:
    namespace: nav-bff-v2
    name: nav-bff-scheduling-services-dev-svc
    labels:
        app: nav-bff-scheduling-services
        cloud: azure
        environment: dev
        cc: 'A04087D476'
        journey: NAV
        oi: '600001290'
        product: NavPacientes
        tier: t0
spec:
    selector:
        app: nav-bff-scheduling-services
    ports:
        - port: 80
          targetPort: 3335
    type: ClusterIP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: nav-bff-scheduling-services-dev-ingress
    namespace: nav-bff-v2
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
        nginx.ingress.kubernetes.io/load-balance: ewma
        nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
        nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
        nginx.ingress.kubernetes.io/proxy-body-size: '1m'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
spec:
    rules:
        - host: nav-bff-scheduling-services.azr-dev02.dasaexp.io
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: nav-bff-scheduling-services-dev-svc
                        servicePort: 80
